import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const ctx=vm.createContext({window:{}});
vm.runInContext(readFileSync('post-format.js','utf8'),ctx);
const f=ctx.window.PostFormat;
const old='## 기존 글\n**그대로** <script>alert(1)</script>';
assert.equal(f.decode(old).format,'plain');
assert.ok(f.render(old).html.includes('## 기존 글'));
assert.ok(!f.render(old).html.includes('<script>'));
const body='## 공부\n**중요**\n[공식 문서](https://example.com)\n```c\nint main() { return 0; }\n```\n![설명](photo:owner%2Fphoto.jpg)';
const saved=f.encode(body,'markdown');
assert.equal(f.decode(saved).text,body);
const rendered=f.render(saved,['owner/photo.jpg','owner/other.jpg']);
assert.match(rendered.html,/<h3>공부<\/h3>/);
assert.match(rendered.html,/<strong>중요<\/strong>/);
assert.match(rendered.html,/<pre><code>int main/);
assert.match(rendered.html,/data-photo="owner\/photo.jpg"/);
assert.deepEqual(Array.from(rendered.remaining),['owner/other.jpg']);
const unsafe=f.render(f.encode('[bad](javascript:alert)\n<img src=x onerror=alert(1)>\n![x](photo:unknown)','markdown'),[]).html;
assert.ok(!unsafe.includes('href="javascript:'));
assert.ok(!unsafe.includes('<img'));
assert.ok(!unsafe.includes('data-photo='));
assert.match(f.render(f.encode('![x](photo:%ZZ)','markdown')).html,/제외된 사진/);
assert.equal(f.encode(old,'plain'),old);
console.log('PASS: legacy text, formatting roundtrip, inline image deduplication, removed images, HTML and URL safety');
